using System.Web;

namespace RequestFlow.Infrastructure
{
    public class InfoHandler : IHttpHandler
    {
        public void ProcessRequest(HttpContext context)
        {
            context.Response.Write("Content generated by InfoHandler");
        }
        public bool IsReusable
        {
            get { return false; }
        }
    }
}